language: cpp

os:
  - linux
  - osx

osx_image: xcode9

compiler:
  - gcc
  - clang

env:
  global:
    - COVERITY_SCAN_PROJECT_NAME="svens/turner"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="sven+turner@alt.ee"
    - COVERITY_SCAN_BRANCH_PATTERN="next"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cov-configure --comptype gcc --compiler gcc-7 --template"
    - COVERITY_SCAN_BUILD_COMMAND="cmake --build ."
    - secure: "UJIpvpvHCFaMwKKcduSz1p5xwZsXKpoNU9sFAKGp9tVsjhlQYcZQ3aGTzk8cku8bLAa+oj0f6cmzwgrMZ4lVyhSZb7xA4cdadJ48RgOeYVpK/CHnebv5HUAqczTtYFPm/4A4nrDPTskp/VK8RQ+cYVAXQylc73Qfr1aihBnJM8zROdF51l5UViggmcsQtRp4KWo//ZEUGEqlqUV5Sa18kDxSscbG7ASnXyynbZzaOj6hEDlPNX1dDbeLIFyzZsEUGAUmeROGs4glgTEWF5EGiqZLUctDz7/PyELCLsbI7Lx4ofpyRhNdHwuNunOs9Oqgeoxtyul4K1plJgfveHhnTe0gaf0dnJgyhqG7USL0u52UdZg/QuaMCugjqte5sGgCFu462itQ1u39sTiNNfEFb6ob3462YMENJZWw2oZqis9Rc6eyXOsUTBYzGIi6wb98UalOQhNSnd0hHMPfAhbMAtjO48vw4iudF/e61ysbbbOVRUTbfUp6cHgxmF6wPmfmZQwpAmZuAYUTVkvnYBiPDBtYmxPs6FCvXIAnCXX4SXV1xE3B5TU5MEID39EpWN7PC5IsRm3IS2Y6i1EAY5rfHqO+TdFWcwMOolRpUMp47MV2Ndb0U+MDvN3ajOXH46AJdro2RuR3jo/HBxsBmbEhZp0U6tA9W1/zF8fsMX/KqIk="
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Coverage
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Coverity

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
      - kalakris-cmake
    packages:
      - clang-5.0
      - cmake
      - g++-7

before_install: |
  if test "${BUILD_TYPE}" = "Coverity"; then
    if test "${TRAVIS_BRANCH}" != "${COVERITY_SCAN_BRANCH_PATTERN}"; then
      exit 0
    fi
    if test "${TRAVIS_PULL_REQUEST}" != "false"; then
      exit 0
    fi
  fi

install: |
  source scripts/travis_install.sh

script: |
  source scripts/travis_script.sh

after_success: |
  source scripts/travis_success.sh
